<?php

/**
 * This is the model base class for the table "usermeta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usermeta".
 *
 * Columns in table "usermeta" available as properties of the model,
 * followed by relations of table "usermeta" available as properties of the model.
 *
 * @property string $usermeta_id
 * @property string $user_id
 * @property string $meta_key
 * @property string $meta_value
 *
 * @property User $user
 */
abstract class BaseUsermeta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usermeta';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usermeta|Usermetas', $n);
	}

	public static function representingColumn() {
		return 'meta_key';
	}

	public function rules() {
		return array(
			array('user_id, meta_key, meta_value', 'required'),
			array('user_id', 'length', 'max'=>20),
			array('meta_key, meta_value', 'length', 'max'=>255),
			array('usermeta_id, user_id, meta_key, meta_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'usermeta_id' => Yii::t('app', 'Usermeta'),
			'user_id' => null,
			'meta_key' => Yii::t('app', 'Meta Key'),
			'meta_value' => Yii::t('app', 'Meta Value'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('usermeta_id', $this->usermeta_id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('meta_key', $this->meta_key, true);
		$criteria->compare('meta_value', $this->meta_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}