<?php

/**
 * This is the model base class for the table "terms".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Term".
 *
 * Columns in table "terms" available as properties of the model,
 * followed by relations of table "terms" available as properties of the model.
 *
 * @property string $term_id
 * @property string $term_taxonomy
 * @property string $term_description
 *
 * @property TermRelationship[] $termRelationships
 */
abstract class BaseTerm extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'terms';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Term|Terms', $n);
	}

	public static function representingColumn() {
		return 'term_taxonomy';
	}

	public function rules() {
		return array(
			array('term_taxonomy', 'required'),
			array('term_taxonomy', 'length', 'max'=>32),
			array('term_description', 'safe'),
			array('term_description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('term_id, term_taxonomy, term_description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'termRelationships' => array(self::HAS_MANY, 'TermRelationship', 'term_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'term_id' => Yii::t('app', 'Term'),
			'term_taxonomy' => Yii::t('app', 'Term Taxonomy'),
			'term_description' => Yii::t('app', 'Term Description'),
			'termRelationships' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('term_id', $this->term_id, true);
		$criteria->compare('term_taxonomy', $this->term_taxonomy, true);
		$criteria->compare('term_description', $this->term_description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}