<?php

/**
 * This is the model base class for the table "siteoptions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Siteoption".
 *
 * Columns in table "siteoptions" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $option_key
 * @property string $option_value
 * @property string $option_autoload
 *
 */
abstract class BaseSiteoption extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'siteoptions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Siteoption|Siteoptions', $n);
	}

	public static function representingColumn() {
		return 'option_value';
	}

	public function rules() {
		return array(
			array('option_key, option_value, option_autoload', 'required'),
			array('option_key, option_value', 'length', 'max'=>255),
			array('option_autoload', 'length', 'max'=>3),
			array('option_key, option_value, option_autoload', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'option_key' => Yii::t('app', 'Option Key'),
			'option_value' => Yii::t('app', 'Option Value'),
			'option_autoload' => Yii::t('app', 'Option Autoload'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('option_key', $this->option_key, true);
		$criteria->compare('option_value', $this->option_value, true);
		$criteria->compare('option_autoload', $this->option_autoload, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}