<?php

/**
 * This is the model base class for the table "comments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comment".
 *
 * Columns in table "comments" available as properties of the model,
 * followed by relations of table "comments" available as properties of the model.
 *
 * @property string $comment_id
 * @property string $comment_post_id
 * @property string $comment_user_id
 * @property string $comment_date
 * @property string $comment_content
 * @property string $comment_status
 * @property string $comment_parent_id
 *
 * @property Post $commentPost
 * @property User $commentUser
 * @property Comment $commentParent
 * @property Comment[] $comments
 */
abstract class BaseComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comment|Comments', $n);
	}

	public static function representingColumn() {
		return 'comment_content';
	}

	public function rules() {
		return array(
			array('comment_post_id, comment_user_id, comment_content', 'required'),
			array('comment_post_id, comment_user_id, comment_status, comment_parent_id', 'length', 'max'=>20),
			array('comment_date', 'safe'),
			array('comment_date, comment_status, comment_parent_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('comment_id, comment_post_id, comment_user_id, comment_date, comment_content, comment_status, comment_parent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'commentPost' => array(self::BELONGS_TO, 'Post', 'comment_post_id'),
			'commentUser' => array(self::BELONGS_TO, 'User', 'comment_user_id'),
			'commentParent' => array(self::BELONGS_TO, 'Comment', 'comment_parent_id'),
			'comments' => array(self::HAS_MANY, 'Comment', 'comment_parent_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'comment_id' => Yii::t('app', 'Comment'),
			'comment_post_id' => null,
			'comment_user_id' => null,
			'comment_date' => Yii::t('app', 'Comment Date'),
			'comment_content' => Yii::t('app', 'Comment Content'),
			'comment_status' => Yii::t('app', 'Comment Status'),
			'comment_parent_id' => null,
			'commentPost' => null,
			'commentUser' => null,
			'commentParent' => null,
			'comments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('comment_id', $this->comment_id, true);
		$criteria->compare('comment_post_id', $this->comment_post_id);
		$criteria->compare('comment_user_id', $this->comment_user_id);
		$criteria->compare('comment_date', $this->comment_date, true);
		$criteria->compare('comment_content', $this->comment_content, true);
		$criteria->compare('comment_status', $this->comment_status, true);
		$criteria->compare('comment_parent_id', $this->comment_parent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}