services:
  database:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: $db_root_password
        MYSQL_DATABASE: $db_name
        MYSQL_USER: $db_user
        MYSQL_PASSWORD: $db_user_password
    volumes:
        - data:/var/lib/mysql
  php:
    image: webdevops/php-apache:7.3-alpine
    ports: 
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/$ROOT_FOLDER
      PHP_DATE_TIMEZONE: America/Sao_Paulo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
    data: